import pandas as pd
import numpy as np
import os
import urllib.request

def download_and_preprocess_omni(num_samples=100000):
    current_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(current_dir, '..', 'data')
    os.makedirs(data_dir, exist_ok=True)
    
    raw_data_path = os.path.join(data_dir, 'omni2_all_years.dat')
    url = 'https://spdf.gsfc.nasa.gov/pub/data/omni/low_res_omni/omni2_all_years.dat'
    
    if not os.path.exists(raw_data_path):
        print(f"Downloading OMNI2 dataset from {url}...")
        urllib.request.urlretrieve(url, raw_data_path)
        print("Download complete.")
        
    print("Parsing dataset...")
    # OMNI2 format: space separated
    df = pd.read_csv(raw_data_path, sep=r'\s+', header=None, engine='python')
    
    # Map required columns based on OMNI2 specification
    # 0: Year, 1: Day, 2: Hour, 16: Bz (GSM), 22: Temperature, 23: Density, 24: Speed
    df = df[[0, 1, 2, 16, 23, 22, 24]]
    df.columns = ['Year', 'Day', 'Hour', 'bz', 'density', 'temperature', 'speed']
    
    print("Cleaning missing values...")
    # Missing values in OMNI2 are encoded as 999.9, 9999.9, or 9999999.
    df['bz'] = df['bz'].replace(999.9, np.nan)
    df['density'] = df['density'].replace(999.9, np.nan)
    df['temperature'] = df['temperature'].replace(9999999., np.nan)
    df['speed'] = df['speed'].replace(9999., np.nan)
    df['speed'] = df['speed'].replace(999.9, np.nan) # Handle various fill values just in case
    
    # Construct timestamp
    # Convert Year, Day, Hour to datetime
    df['timestamp'] = pd.to_datetime(df['Year'].astype(str) + df['Day'].astype(str).str.zfill(3), format='%Y%j') + pd.to_timedelta(df['Hour'], unit='h')
    
    # Drop original time columns
    df.drop(columns=['Year', 'Day', 'Hour'], inplace=True)
    
    # Forward fill small gaps (up to 3 hours), then drop remaining NaNs
    df.ffill(limit=3, inplace=True)
    df.dropna(inplace=True)
    
    print("Filtering to recent records...")
    # Take the most recent 'num_samples' valid records
    df = df.tail(num_samples).copy()
    
    print("Feature Engineering...")
    df['speed_t-1'] = df['speed'].shift(1)
    df['speed_t-2'] = df['speed'].shift(2)
    df['density_t-1'] = df['density'].shift(1)
    df['bz_t-1'] = df['bz'].shift(1)
    
    # Target: Predict speed 1 hour into the future
    df['target_speed'] = df['speed'].shift(-1)
    
    # Drop NaNs generated by shifting
    df.dropna(inplace=True)
    
    output_path = os.path.join(data_dir, 'space_weather_real.csv')
    df.to_csv(output_path, index=False)
    print(f"Real data processed and saved to {output_path}. Shape: {df.shape}")
    return df

if __name__ == "__main__":
    download_and_preprocess_omni(100000)
